name: Simple CRUD backend CI

on: [push]

defaults:
  run:
    working-directory: ./crud_backend

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: Run Pytest
        run: uv run pytest .
        env:
          USERNAME_DB: "UserTest"
          PASSWORD_DB: "PasswordTest123"
          ROOT_PASSWORD_DB: "RootTest123"
          HOST_DB: "localhost"
          PORT_DB: "3306"
          DATABASE: "simple_crud_test"

  linter:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: Run Ruff
        run: uv run ruff check .

  security:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install UV and Dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv .venv
          uv sync --all-groups
      - name: run Bandit
        run: uv run bandit -r src/